# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "5380:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "53443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      - "67:67/udp"
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: 'Europe/Paris'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'admin'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - pihole:/etc/pihole
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
    networks:
      no_internet_access:
         ipv4_address: 172.22.0.53
    #dns:
    #   - 127.0.0.1
    #dns_search: intranet.local
    #domainname: intranet.local
    extra_hosts:
        - host.docker.internal:host-gateway

  bind9:
    container_name: bind9
    hostname: bind9
    image: localhost:5000/jinade_bind9-debug_debian:latest
    ports:
      # DNS Ports
      - "5353:53/tcp"
      - "5353:53/udp"
    environment:
      TZ: 'Europe/Paris'
    restart: unless-stopped
    networks:
      no_internet_access:
         ipv4_address: 172.22.0.54
      internet_access:
         ipv4_address: 172.42.0.53
#    dns:
#       - 127.0.0.1
#    dns_search: intranet.local
#    domainname: intranet.local
    extra_hosts:
        - host.docker.internal:host-gateway

volumes:
    pihole:
        external: true
        name: pihole

networks:
    no_internet_access:
        external: true
        name: no_internet_access
    internet_access:
        external: true
        name: internet_access
